"use client";

import { useState } from "react";

interface AiSummaryResponse {
  summary: string;
  model: string;
}

interface AiSummaryError {
  error: string;
}

export function AiSummary() {
  const [loading, setLoading] = useState(false);
  const [summary, setSummary] = useState<AiSummaryResponse | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleSummarize = async () => {
    setLoading(true);
    setError(null);
    setSummary(null);

    try {
      const response = await fetch("/api/ai/summary", { method: "POST" });

      if (response.status === 503) {
        setError("AI summaries are not configured on this instance.");
        return;
      }

      if (!response.ok) {
        setError("Failed to generate summary. Please try again.");
        return;
      }

      const data: AiSummaryResponse | AiSummaryError = await response.json();

      if ("error" in data) {
        setError("Failed to generate summary. Please try again.");
      } else {
        setSummary(data);
      }
    } catch {
      setError("Failed to generate summary. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="card bg-base-100 border border-base-300">
      <div className="card-body">
        <div className="flex items-center justify-between mb-4">
          <h3 className="card-title">AI Summary</h3>
          <button
            className="btn btn-outline btn-sm"
            onClick={handleSummarize}
            disabled={loading}
          >
            {loading ? (
              <>
                <span className="loading loading-spinner loading-sm"></span>
                Generating...
              </>
            ) : (
              <>✨ Summarize with AI</>
            )}
          </button>
        </div>

        {error && (
          <div
            className={`text-sm ${
              error.includes("not configured")
                ? "text-base-content/60"
                : "text-error"
            }`}
          >
            {error}
          </div>
        )}

        {summary && (
          <div>
            <p className="text-base">{summary.summary}</p>
            <p className="text-xs text-base-content/50 mt-4">
              Generated by {summary.model}
            </p>
          </div>
        )}

        {!summary && !error && !loading && (
          <p className="text-sm text-base-content/60">
            Click the button above to generate an AI summary of your system
            status.
          </p>
        )}
      </div>
    </div>
  );
}
